### ISSUE TITLE
@Transient does not always work.

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#145]
I have extends a `User` entity using [InetOrgPerson](https://github.com/spring-projects/spring-security/blob/master/ldap/src/main/java/org/springframework/security/ldap/userdetails/InetOrgPerson.java#L31)

 [InetOrgPerson](https://github.com/spring-projects/spring-security/blob/master/ldap/src/main/java/org/springframework/security/ldap/userdetails/InetOrgPerson.java#L31) inherit from [Person](https://github.com/spring-projects/spring-security/blob/master/ldap/src/main/java/org/springframework/security/ldap/userdetails/Person.java#L37).

I have created a **InetOrgPersonMybatis** class that look like follow: 

```java
public class InetOrgPersonMybatis extends InetOrgPerson {

    @Transient
    private String carLicense;
    // Person.cn

    @Transient
    private String destinationIndicator;

    @Transient
    private String departmentNumber;
    // Person.description

    @Transient
    private String displayName;

    @Transient
    private String employeeNumber;

    @Transient
    private String homePhone;

    @Transient
    private String homePostalAddress;

    @Transient
    private String initials;

    @Transient
    private String mail;

    @Transient
    private String mobile;

    @Transient
    private String o;

    @Transient
    private String ou;

    @Transient
    private String postalAddress;

    @Transient
    private String postalCode;

    @Transient
    private String roomNumber;

    @Transient
    private String street;
    // Person.sn
    // Person.telephoneNumber

    @Transient
    private String title;

    @Transient
    private String uid;

    @Transient
    private String givenName;

    @Transient
    private String sn;

    @Transient
    private String description;

    @Transient
    private String telephoneNumber;

    @Transient
    private List<String> cn = new ArrayList<>();

    @Transient
    @Override
    public String[] getCn() {
        return cn.toArray(new String[cn.size()]);
    }

    @Transient
    private String dn;

    @Transient
    private String password;

    private String username;

    @Transient
    private Collection<GrantedAuthority> authorities = AuthorityUtils.NO_AUTHORITIES;

    @Transient
    public Collection<GrantedAuthority> getAuthorities() {
        return authorities;
    }

    @Transient
    private boolean accountNonExpired = true;

    @Transient
    private boolean accountNonLocked = true;

    @Transient
    private boolean credentialsNonExpired = true;

    @Transient
    private boolean enabled = true;

    // PPolicy data
    @Transient
    private int timeBeforeExpiration = Integer.MAX_VALUE;

    @Transient
    private int graceLoginsRemaining = Integer.MAX_VALUE;

}
```

This produce the following error : 

```
Caused by: org.springframework.data.mapping.model.MappingException: create auto mapping error for com.domain.domain.User
	at org.springframework.data.mybatis.repository.support.MybatisSimpleRepositoryMapperGenerator.generate(MybatisSimpleRepositoryMapperGenerator.java:100)
	at org.springframework.data.mybatis.repository.support.MybatisRepositoryFactory.getTargetRepository(MybatisRepositoryFactory.java:79)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:199)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:277)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:263)
	at org.springframework.data.mybatis.repository.support.MybatisRepositoryFactoryBean.afterPropertiesSet(MybatisRepositoryFactoryBean.java:64)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 48 common frames omitted
Caused by: org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: java.lang.IllegalStateException: Type handler was null on parameter mapping for property 'cn'. It was either not specified and/or could not be found for the javaType ([Ljava.lang.String;) : jdbcType (VARCHAR) combination.
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:120)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.parse(XMLMapperBuilder.java:92)
	at org.springframework.data.mybatis.repository.support.MybatisSimpleRepositoryMapperGenerator.generate(MybatisSimpleRepositoryMapperGenerator.java:98)
	... 55 common frames omitted
Caused by: java.lang.IllegalStateException: Type handler was null on parameter mapping for property 'cn'. It was either not specified and/or could not be found for the javaType ([Ljava.lang.String;) : jdbcType (VARCHAR) combination.
	at org.apache.ibatis.mapping.ParameterMapping$Builder.validate(ParameterMapping.java:119)
	at org.apache.ibatis.mapping.ParameterMapping$Builder.build(ParameterMapping.java:104)
	at org.apache.ibatis.builder.SqlSourceBuilder$ParameterMappingTokenHandler.buildParameterMapping(SqlSourceBuilder.java:123)
	at org.apache.ibatis.builder.SqlSourceBuilder$ParameterMappingTokenHandler.handleToken(SqlSourceBuilder.java:67)
	at org.apache.ibatis.parsing.GenericTokenParser.parse(GenericTokenParser.java:78)
	at org.apache.ibatis.builder.SqlSourceBuilder.parse(SqlSourceBuilder.java:45)
	at org.apache.ibatis.scripting.defaults.RawSqlSource.<init>(RawSqlSource.java:46)
	at org.apache.ibatis.scripting.defaults.RawSqlSource.<init>(RawSqlSource.java:40)
	at org.apache.ibatis.scripting.xmltags.XMLScriptBuilder.parseScriptNode(XMLScriptBuilder.java:58)
	at org.apache.ibatis.scripting.xmltags.XMLLanguageDriver.createSqlSource(XMLLanguageDriver.java:44)
	at org.apache.ibatis.builder.xml.XMLStatementBuilder.parseStatementNode(XMLStatementBuilder.java:94)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.buildStatementFromContext(XMLMapperBuilder.java:135)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.buildStatementFromContext(XMLMapperBuilder.java:128)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:118)
	... 57 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:40837', transport: 'socket'

Process finished with exit code 0
```

Version : 

spring-boot-starter-data-mybatis | 1.0.17.RELEASE

**Comment by kopax** [comment]
Hi @easybest ? Can you make this project open to others a little bit :place_of_worship:
