### ISSUE TITLE
springboot2.0 环境中整合报错

### ISSUE THREAD

**Issue by huyaro** [easybest/spring-data-mybatis#169]
是否可以给出一个基于springboot2.0环境的示例程序？
当前链接指向的示例程序还是之前的版本。

maven parent：
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.0.3.RELEASE</version>
  </parent>

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration]: No default constructor found; nested exception is java.lang.**NoSuchMethodException**: org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration.<init>()
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1238)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1137)

**Comment by huyaro** [comment]
已解决。因为Dialect未配置的原因导致无法initBean。

**Comment by easybest** [comment]
当前版本还没有完全完成，预计本月完成。
