### ISSUE TITLE
Bug non mapped attribute request a typeHandler

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#45]
I have a case where an attribute `translateMessage` is not stored in the database.

```
public abstract class I18nId extends LongId implements Cloneable, TranslateMessageInterface {

	private static final Logger logger = LoggerFactory.getLogger(I18nId.class);

	@JdbcType(VARCHAR)
	@Column(name = "I18N_ID")
	@NotNull
	@JsonIgnore
	private String messageId;

	private TranslateMessage translateMessage;

	public String getMessageId() {
		return messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	public void setTranslateMessage(TranslateMessage translateMessage) {
		this.translateMessage = translateMessage;
	}

	public TranslateMessage getTranslateMessage() {
		if (null == translateMessage) {
			translateMessage = new TranslateMessage(getMessageId(), getDefaultMessage());
		}
		return translateMessage;
	}
}
```

This will throw the error :

```ruby
Caused by: org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: java.lang.IllegalStateException: No typehandler found for property translateMessage
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:120)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.parse(XMLMapperBuilder.java:92)
	at org.springframework.data.mybatis.repository.support.MybatisSimpleRepositoryMapperGenerator.generate(MybatisSimpleRepositoryMapperGenerator.java:98)
	... 37 common frames omitted
Caused by: java.lang.IllegalStateException: No typehandler found for property translateMessage
	at org.apache.ibatis.mapping.ResultMapping$Builder.validate(ResultMapping.java:151)
	at org.apache.ibatis.mapping.ResultMapping$Builder.build(ResultMapping.java:140)
	at org.apache.ibatis.builder.MapperBuilderAssistant.buildResultMapping(MapperBuilderAssistant.java:382)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.buildResultMappingFromContext(XMLMapperBuilder.java:378)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.resultMapElement(XMLMapperBuilder.java:280)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.resultMapElement(XMLMapperBuilder.java:252)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.resultMapElements(XMLMapperBuilder.java:244)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:116)
	... 39 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:48342', transport: 'socket'
```

I fixed it by not creating an attribute and returning a new Instance of `TranslateMessage` everytime the getter is called.

**Comment by easybest** [comment]
add @Transit

**Comment by easybest** [comment]
add @Transient annotation to igonore unpersistent attribute.

**Comment by kopax** [comment]
My bad, it work with __@Transient__
